// Pump-flow calibration profile + analysis math.
// Profile is embedded so the calibration is reproducible regardless of which
// profiles the user has loaded. Math mirrors the original `analyze.js` shared
// in the GaggiMate community (see calibrate.js bookmarklet).

export const CALIBRATION_PROFILE_ID = 'pump-flow-calibration';

export const CALIBRATION_PROFILE = {
  id: CALIBRATION_PROFILE_ID,
  label: '[Calibration] Pump flow calibration',
  type: 'pro',
  description: 'Auto-generated by the pump flow calibration tool.',
  temperature: 30,
  phases: [
    {
      name: 'Build 1 bar',
      phase: 'preinfusion',
      valve: 0,
      duration: 20,
      temperature: 0,
      transition: { type: 'ease-out', duration: 5, adaptive: true },
      pump: { target: 'pressure', pressure: 1, flow: 0 },
      targets: [{ type: 'pressure', operator: 'gte', value: 1 }],
    },
    {
      name: 'Settle 1 bar',
      phase: 'preinfusion',
      valve: 0,
      duration: 5,
      temperature: 0,
      transition: { type: 'instant', duration: 0, adaptive: true },
      pump: { target: 'pressure', pressure: 1, flow: 0 },
    },
    {
      name: 'Measure 1 bar',
      phase: 'brew',
      valve: 0,
      duration: 10,
      temperature: 25,
      transition: { type: 'instant', duration: 0, adaptive: true },
      pump: { target: 'pressure', pressure: 1, flow: 0 },
    },
    {
      name: 'Settle 1 bar',
      phase: 'brew',
      valve: 0,
      duration: 5,
      temperature: 0,
      transition: { type: 'instant', duration: 0, adaptive: true },
      pump: { target: 'pressure', pressure: 1, flow: 0 },
    },
    {
      name: 'Build 9 bar',
      phase: 'brew',
      valve: 0,
      duration: 20,
      temperature: 0,
      transition: { type: 'ease-out', duration: 5, adaptive: true },
      pump: { target: 'pressure', pressure: 9, flow: 0 },
      targets: [{ type: 'pressure', operator: 'gte', value: 9 }],
    },
    {
      name: 'Settle 9 bar',
      phase: 'brew',
      valve: 0,
      duration: 5,
      temperature: 0,
      transition: { type: 'instant', duration: 0, adaptive: true },
      pump: { target: 'pressure', pressure: 9, flow: 0 },
    },
    {
      name: 'Measure 9 bar',
      phase: 'brew',
      valve: 0,
      duration: 10,
      temperature: 25,
      transition: { type: 'instant', duration: 0, adaptive: true },
      pump: { target: 'pressure', pressure: 9, flow: 0 },
    },
    {
      name: 'Settle 9 bar',
      phase: 'brew',
      valve: 0,
      duration: 5,
      temperature: 0,
      transition: { type: 'instant', duration: 0, adaptive: true },
      pump: { target: 'pressure', pressure: 9, flow: 0 },
    },
  ],
};

// Filters a parsed shot for samples in a "Measure X bar" phase
// (target temp = 25 °C, target pressure = X bar) and computes the calibration
// factor from real flow (delta volume / delta time) vs. estimated flow
// (integral of reported pump flow). Caller multiplies the existing coefficient
// for that pressure point by this factor to get the new coefficient.
export function analyze(samples, targetPressure) {
  const measure = samples.filter(s => s.tt === 25 && s.tp === targetPressure);
  if (measure.length < 2) {
    throw new Error(
      `Not enough samples for tp=${targetPressure} bar (Measure phase). Was the valve closed enough to reach ${targetPressure} bar?`,
    );
  }
  const first = measure[0];
  const last = measure[measure.length - 1];
  const volume = last.v - first.v;
  const time = (last.t - first.t) / 1000;
  let pumped = 0;
  let lastT = 0;
  for (const s of measure) {
    if (lastT !== 0) pumped += (s.fl / 1000) * (s.t - lastT);
    lastT = s.t;
  }
  const actualFlow = volume / time;
  const estimatedFlow = pumped / time;
  return { volume, time, actualFlow, estimatedFlow, factor: actualFlow / estimatedFlow };
}
